version: '3.9'
services:
  final_pweb_api:
    image: final_pweb_api
    container_name: final_pweb_api
    depends_on:
      - sql_server
    ports:
      - 8086:80
    networks:
      - proiect-pweb

networks:
  proiect-pweb:
    external: true